import type { AppStoreActions } from '../../app-store-contract';
import type { AppStoreOperations } from './engine-context';
export function createAppStoreCommands(operations: AppStoreOperations): AppStoreActions {
  return {
    retryLoad: operations.retryLoad,
    retrySave: operations.retrySave,
    retrySleepReminderSync: operations.retrySleepReminderSync,
    saveDay: operations.saveDay,
    saveDays: operations.saveDays,
    updatePattern: operations.updatePattern,
    updatePatternDetailed: operations.updatePatternDetailed,
    updateShiftTypes: operations.updateShiftTypes,
    updateShiftSettings: operations.updateShiftSettings,
    updatePayrollSettings: operations.updatePayrollSettings,
    dismissPlayUpdate: operations.dismissPlayUpdate,
    setThemeMode: operations.setThemeMode,
    toggleWidgetDisplayOption: operations.toggleWidgetDisplayOption,
    completeSetup: operations.completeSetup,
    completeInitialSetup: operations.completeInitialSetup,
    commitSetup: operations.commitSetup,
    getAlarmStatus: operations.getAlarmStatus,
    requestAlarmAccess: operations.requestAlarmAccess,
    resyncAlarms: operations.resyncAlarms,
    enableAlarms: operations.enableAlarms,
    disableAlarms: operations.disableAlarms,
    setSleepReminderEnabled: operations.setSleepReminderEnabled,
    sendTestAlarm: operations.sendTestAlarm,
    exportData: operations.exportData,
    previewImportData: operations.previewImportData,
    importData: operations.importData,
    exportSharedWorkSettings: operations.exportSharedWorkSettings,
    previewSharedWorkSettings: operations.previewSharedWorkSettings,
    applySharedWorkSettings: operations.applySharedWorkSettings,
    saveUserPattern: operations.saveUserPattern,
    importValidatedPattern: operations.importValidatedPattern,
    deletePattern: operations.deletePattern,
    previewPatternApplication: operations.previewPatternApplication,
    applyPatternFromVault: operations.applyPatternFromVault,
    rollbackLastPatternApplication: operations.rollbackLastPatternApplication,
    createBackup: operations.createBackup,
    createBackupBeforeReset: operations.createBackup,
    getLatestBackupPreview: operations.getLatestBackupPreview,
    getPendingRestoreBackupPreview: operations.getPendingRestoreBackupPreview,
    getRecoveryBackupPreview: operations.getRecoveryBackupPreview,
    restoreLatestBackup: operations.restoreLatestBackup,
    retryPendingRestoreBackup: operations.retryPendingRestoreBackup,
    restoreRecoveryBackup: operations.restoreRecoveryBackup,
    startFreshAfterLoadError: operations.startFreshAfterLoadError,
    resetAllData: operations.resetAllData,
    resetAllDataDetailed: operations.resetAllDataDetailed,
  };
}
